#%RAML 1.0 DataType
description: Book object
type: object
properties:
  id:
    required: true
    type: integer
  name:
    required: true
    type: string
  edition: integer
  year: integer
  language: string
  isbn: string
